### PR TITLE
fix active button text color

### LINKED ISSUE #228: Button: Update color for active states (From #2152)
Update text color for all button active states to text-strong (#000000) based on design update in #2152

### PR DESCRIPTION
**Pull request by britt6612**
#### What does this PR do?
update active button to have text `text-strong` 
#### What testing has been done on this PR?
tested in the design system site
#### Any background context you want to provide?
designs call for `text-strong`
#### What are the relevant issues?
closes #228 
#### Is this change backward compatible or could it be a breaking change for the official HPE theme?
It will change how active button was before
#### How should this PR be communicated in the release notes?
yes

### CODE REVIEW

**Review by ericsoderberghp — APPROVED** [review]

File: src/js/themes/hpe.js [hunk 1]
```diff
@@ -208,7 +208,7 @@ export const hpe = deepFreeze({
       background: {
         color: 'background-contrast',
       },
-      color: 'text',
+      color: 'text-stong',
```
Comment (taysea) [inline src/js/themes/hpe.js:211]:
```suggestion
      color: 'text-strong',
```
